# Generated by Django 3.2 on 2021-04-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminsection', '0003_invoice_billingnumber'),
        ('adminsection', '0004_auto_20200131_0814'),
    ]

    operations = [
    ]
