# Generated by Django 3.2 on 2021-04-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0003_appoinment_appointmentnumber'),
        ('parlour', '0014_auto_20200125_2045'),
    ]

    operations = [
    ]
